"""Output for ioc-enrich: terminal table, JSON, CSV and Markdown."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Callable, Sequence

from soc_toolkit import __version__
from soc_toolkit.common.output import md_table, to_json
from soc_toolkit.ioc_enrich.extract import defang
from soc_toolkit.ioc_enrich.models import Enrichment

CSV_FIELDS = ("ioc", "type", "verdict", "score", "malicious_sources", "suspicious_sources", "summary", "links", "note")
_ORDER = {"malicious": 0, "suspicious": 1, "unknown": 2, "harmless": 3}


def sort_enrichments(items: Sequence[Enrichment]) -> list[Enrichment]:
    return sorted(items, key=lambda e: (_ORDER.get(e.verdict, 9), -e.score, e.indicator.type, e.indicator.value))


def _display(e: Enrichment, defanged: bool) -> str:
    return defang(e.indicator) if defanged else e.indicator.value


def headline(e: Enrichment) -> str:
    """The most useful one-line explanation: the strongest hits first."""
    hits = [r for r in e.results if r.status == "hit"]
    hits.sort(key=lambda r: -(r.score or 0))
    if hits:
        return "; ".join(f"{r.provider}: {r.summary}" for r in hits[:3])
    if e.note:
        return e.note
    clean = [r for r in e.results if r.status == "clean" and r.summary]
    if clean:
        return "; ".join(f"{r.provider}: {r.summary}" for r in clean[:2])
    errors = [r for r in e.results if r.status == "error"]
    if errors:
        return "; ".join(f"{r.provider}: {r.summary}" for r in errors[:2])
    return "no feed knows this indicator"


def csv_rows(items: Sequence[Enrichment], defanged: bool) -> list[dict]:
    return [{"ioc": _display(e, defanged), "type": e.indicator.type, "verdict": e.verdict, "score": e.score,
             "malicious_sources": e.sources("malicious"), "suspicious_sources": e.sources("suspicious"),
             "summary": headline(e), "links": [r.link for r in e.results if r.link], "note": e.note} for e in items]


def render_json(items: Sequence[Enrichment], defanged: bool) -> str:
    data = []
    for e in items:
        d = e.to_dict()
        d["display"] = _display(e, defanged)
        data.append(d)
    return to_json({"tool": "ioc-enrich", "version": __version__,
                    "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"), "results": data})


def render_markdown(items: Sequence[Enrichment], providers: Sequence[str], defanged: bool) -> str:
    counts = {v: sum(1 for e in items if e.verdict == v) for v in ("malicious", "suspicious", "unknown", "harmless")}
    lines = ["# IOC enrichment report", "",
             f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · "
             f"**Indicators:** {len(items)} · **Feeds:** {', '.join(providers) or 'none'}", "",
             md_table(["Verdict", "Count"], [(k, v) for k, v in counts.items()]), "",
             "## Results", "",
             md_table(["Verdict", "Score", "Type", "Indicator", "Why"],
                      [(e.verdict, e.score, e.indicator.type, f"`{_display(e, defanged)}`", headline(e)) for e in items]),
             "", "## Detail", ""]
    for e in items:
        if not e.results:
            continue
        lines += [f"### `{_display(e, defanged)}` - {e.verdict} ({e.score})", ""]
        lines.append(md_table(["Feed", "Status", "Verdict", "Score", "Summary", "Link"],
                              [(r.provider + (" (cached)" if r.cached else ""), r.status, r.verdict,
                                "" if r.score is None else r.score, r.summary, r.link) for r in e.results]))
        lines.append("")
    lines += ["---", f"Generated by soc-toolkit `ioc-enrich` {__version__}. Lookups only: nothing was submitted to any feed."]
    return "\n".join(lines)


def print_table(items: Sequence[Enrichment], paint: Callable[[str, str], str], defanged: bool, width: int = 60) -> None:
    print(f"{'VERDICT':<11} {'SCORE':>5}  {'TYPE':<7} {'INDICATOR':<{width}}  WHY")
    for e in items:
        value = _display(e, defanged)
        if len(value) > width:
            value = value[: width - 3] + "..."
        print(f"{paint(e.verdict, f'{e.verdict:<11}')} {e.score:>5}  {e.indicator.type:<7} {value:<{width}}  {headline(e)}")
