"""Shared Markdown / CSV / JSON report for finding-based audits (entra-audit, mde-health)."""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import Any, Iterable, Sequence

from soc_toolkit import __version__
from soc_toolkit.common.findings import SEVERITIES, Finding, count_by_severity
from soc_toolkit.common.output import md_table, to_json, write_csv, write_text

FINDING_FIELDS = ("severity", "check", "title", "target", "detail", "recommendation")
_BADGE = {"critical": "🟥 critical", "high": "🟧 high", "medium": "🟨 medium", "low": "🟦 low", "info": "⬜ info"}


def render_markdown(title: str, meta: Sequence[tuple[str, Any]], stats: Sequence[tuple[str, Any]],
                    findings: Sequence[Finding], notes: Iterable[str], tool: str) -> str:
    counts = count_by_severity(findings)
    lines = [f"# {title}", ""]
    lines.append(" · ".join(f"**{k}:** {v}" for k, v in meta if v not in (None, "")))
    lines += ["", "## Summary", ""]
    lines.append(md_table(["Severity", "Findings"], [(_BADGE[s], counts[s]) for s in SEVERITIES]))
    if stats:
        lines += ["", md_table(["Measure", "Value"], [(k, "n/a" if v is None else v) for k, v in stats])]
    groups: "OrderedDict[str, list[Finding]]" = OrderedDict()
    for f in findings:
        groups.setdefault(f.title, []).append(f)
    lines += ["", "## Findings", ""]
    if not findings:
        lines.append("No findings. 🎉")
    for group_title, items in groups.items():
        lines += [f"### {group_title} ({len(items)})", "", f"_Check: `{items[0].check}`. "
                  f"Recommendation: {items[0].recommendation}_", ""]
        lines.append(md_table(["Severity", "Target", "Detail"],
                              [(_BADGE.get(f.severity, f.severity), f.target, f.detail) for f in items]))
        lines.append("")
    note_list = list(notes)
    if note_list:
        lines += ["## Coverage notes", "", "Parts of the audit could not run; results for them are incomplete:", ""]
        lines += [f"- {n}" for n in note_list]
        lines.append("")
    lines += ["---", f"Generated by soc-toolkit `{tool}` {__version__}. Read-only: nothing was changed."]
    return "\n".join(lines)


def write_reports(out_dir: Path, stem: str, formats: Sequence[str], markdown: str,
                  payload: dict[str, Any], findings: Sequence[Finding]) -> list[Path]:
    written: list[Path] = []
    if "md" in formats:
        path = out_dir / f"{stem}.md"
        write_text(path, markdown)
        written.append(path)
    if "csv" in formats:
        path = out_dir / f"{stem}.csv"
        write_csv(path, (f.to_dict() for f in findings), FINDING_FIELDS)
        written.append(path)
    if "json" in formats:
        path = out_dir / f"{stem}.json"
        write_text(path, to_json(payload))
        written.append(path)
    return written


def print_summary(findings: Sequence[Finding], paint_fn, limit: int = 15) -> None:
    counts = count_by_severity(findings)
    print("Findings: " + ", ".join(paint_fn(s, f"{counts[s]} {s}") for s in SEVERITIES))
    for f in findings[:limit]:
        print(f"  {paint_fn(f.severity, f'[{f.severity:<8}]')} {f.title}: {f.target}")
    if len(findings) > limit:
        print(f"  ... and {len(findings) - limit} more in the report")
